### PR TITLE
Add experiment-as-flag for Fx 38.1/iOS launch.

### PR DESCRIPTION
**Pull request by jpetto**
_Do not merge_

Preparing for Fx 38.1 launch. Will likely need to at least add time to `startDate` of new flag/experiment. 

Would love code review though to make sure this is the right approach.

### CODE REVIEW

**Comment by dannycoates** [comment]
``` js
module.exports = {
  name: 'Has Firefox for iOS launched',
  independentVariables: ['isFxIosLaunched'],
  endDate: '2015-06-02',
  conclusion: {
    isFxIosLaunched: true
  }
};
```

This ought to be the minimal spec for what I think you're trying to do. Its saying something like this in pseudo-english-code:

> This experiment (which never actually started) should end on '2015-06-02'. Before the startDate (same as endDate in this case) the variable 'isFxIosEnabled' is set to the default value (from defaults.json), after the endDate it is set to true (the conclusion).

This [cookbook](https://github.com/dannycoates/abatar/blob/master/doc/cookbook.md) shows how to do a few scenarios, though I need to update a few details that have changed recently.

**Comment by jpetto** [comment]
In the `fxa-content-server` repo, I was getting errors when omitting the `eligibilityFunction` and `groupingFunction` keys. It looks like the [lib included in that repo](https://github.com/dannycoates/able) requires those keys - I was getting errors in the [`experimentDefinition` function](https://github.com/dannycoates/able/blob/master/project.js#L169).

The cookbook you pointed to looks like a slightly different lib, but might have the same requirement/problem?

Is the `fxa-content-server` repo using an outdated lib?

**Comment by dannycoates** [comment]
> I was getting errors when omitting the eligibilityFunction and groupingFunction keys

Yep, that was a bug. Its fixed in `able@0.4.1` and should get deployed in the next release (train-37). In the meantime your workaround works fine.

**Comment by jpetto** [comment]
Closing in favor of PR #3.

(A similar PR will likely be opened when Fx iOS eventually launches.)

**Pull request closed without merging**
